//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAttributes
    {
        public int CategoryID { get; set; }
        public int AttributeID { get; set; }
        public byte AttributeScope { get; set; }
        public bool IsRequired { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ProductAttributes ProductAttributes { get; set; }
    }
}
