//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransactions
    {
        public long InventoryTransactionID { get; set; }
        public int WarehouseID { get; set; }
        public int VariantID { get; set; }
        public byte TransactionType { get; set; }
        public int QuantityChange { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> AverageUnitCostAfter { get; set; }
        public int BalanceAfter { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public string Note { get; set; }
        public string CreatedByUserID { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ProductVariants ProductVariants { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
