//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryStocks
    {
        public int InventoryStockID { get; set; }
        public int WarehouseID { get; set; }
        public int VariantID { get; set; }
        public int QuantityOnHand { get; set; }
        public int ReservedQuantity { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ProductVariants ProductVariants { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
