//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListItems
    {
        public long PriceListItemID { get; set; }
        public int PriceListID { get; set; }
        public int VariantID { get; set; }
        public decimal SellingPrice { get; set; }
        public Nullable<decimal> CompareAtPrice { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual PriceLists PriceLists { get; set; }
        public virtual ProductVariants ProductVariants { get; set; }
    }
}
