//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecifications
    {
        public int ProductSpecificationID { get; set; }
        public int ProductID { get; set; }
        public int AttributeID { get; set; }
        public string Value { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ProductAttributes ProductAttributes { get; set; }
        public virtual Products Products { get; set; }
    }
}
