//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDisposals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockDisposals()
        {
            this.StockDisposalDetails = new HashSet<StockDisposalDetails>();
        }
    
        public int StockDisposalID { get; set; }
        public string DisposalCode { get; set; }
        public int WarehouseID { get; set; }
        public System.DateTime DisposalDate { get; set; }
        public string Reason { get; set; }
        public string Note { get; set; }
        public byte Status { get; set; }
        public string CreatedByUserID { get; set; }
        public string ConfirmedByUserID { get; set; }
        public string CancelledByUserID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> ConfirmedAt { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDisposalDetails> StockDisposalDetails { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
