//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockIns()
        {
            this.StockInDetails = new HashSet<StockInDetails>();
        }
    
        public int StockInID { get; set; }
        public string StockInCode { get; set; }
        public int SupplierID { get; set; }
        public int WarehouseID { get; set; }
        public System.DateTime StockInDate { get; set; }
        public byte Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> ConfirmedByUserID { get; set; }
        public Nullable<int> CancelledByUserID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> ConfirmedAt { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInDetails> StockInDetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
