//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockInDetails()
        {
            this.StockReturnDetails = new HashSet<StockReturnDetails>();
        }
    
        public int StockInDetailID { get; set; }
        public int StockInID { get; set; }
        public int VariantID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
    
        public virtual ProductVariants ProductVariants { get; set; }
        public virtual StockIns StockIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockReturnDetails> StockReturnDetails { get; set; }
    }
}
