//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReturnDetails
    {
        public int StockReturnDetailID { get; set; }
        public int StockReturnID { get; set; }
        public int VariantID { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<int> SourceOrderDetailID { get; set; }
        public Nullable<int> SourceStockInDetailID { get; set; }
    
        public virtual ProductVariants ProductVariants { get; set; }
        public virtual StockInDetails StockInDetails { get; set; }
        public virtual StockReturns StockReturns { get; set; }
    }
}
