//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOuts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockOuts()
        {
            this.StockOutDetails = new HashSet<StockOutDetails>();
        }
    
        public int StockOutID { get; set; }
        public string StockOutCode { get; set; }
        public int WarehouseID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public System.DateTime StockOutDate { get; set; }
        public byte StockOutType { get; set; }
        public byte Status { get; set; }
        public string Note { get; set; }
        public string CreatedByUserID { get; set; }
        public string ConfirmedByUserID { get; set; }
        public string CancelledByUserID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> ConfirmedAt { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutDetails> StockOutDetails { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
