//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechStoreDBEntities : DbContext
    {
        public TechStoreDBEntities()
            : base("name=TechStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttributeValues> AttributeValues { get; set; }
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<BranchPriceLists> BranchPriceLists { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CategoryAttributes> CategoryAttributes { get; set; }
        public virtual DbSet<InventoryStocks> InventoryStocks { get; set; }
        public virtual DbSet<InventoryTransactions> InventoryTransactions { get; set; }
        public virtual DbSet<PriceListItems> PriceListItems { get; set; }
        public virtual DbSet<PriceLists> PriceLists { get; set; }
        public virtual DbSet<ProductAttributes> ProductAttributes { get; set; }
        public virtual DbSet<ProductImages> ProductImages { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSpecifications> ProductSpecifications { get; set; }
        public virtual DbSet<ProductVariants> ProductVariants { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<StockDisposalDetails> StockDisposalDetails { get; set; }
        public virtual DbSet<StockDisposals> StockDisposals { get; set; }
        public virtual DbSet<StockInDetails> StockInDetails { get; set; }
        public virtual DbSet<StockIns> StockIns { get; set; }
        public virtual DbSet<StockOutDetails> StockOutDetails { get; set; }
        public virtual DbSet<StockOuts> StockOuts { get; set; }
        public virtual DbSet<StockReturnDetails> StockReturnDetails { get; set; }
        public virtual DbSet<StockReturns> StockReturns { get; set; }
        public virtual DbSet<StockTransferDetails> StockTransferDetails { get; set; }
        public virtual DbSet<StockTransfers> StockTransfers { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VariantAttributes> VariantAttributes { get; set; }
        public virtual DbSet<VariantCosts> VariantCosts { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
    }
}
