//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantAttributes
    {
        public int VariantID { get; set; }
        public int AttributeID { get; set; }
        public int AttributeValueID { get; set; }
    
        public virtual ProductAttributes ProductAttributes { get; set; }
        public virtual ProductVariants ProductVariants { get; set; }
    }
}
