//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantCosts
    {
        public int VariantID { get; set; }
        public decimal AverageUnitCost { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ProductVariants ProductVariants { get; set; }
    }
}
